services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB : desafio
      POSTGRES_USERNAME : postgres
      POSTGRES_PASSWORD : 123

  # backend: